[workspace]
resolver = "2"
members = [
    "core",
    "serde",
    "esc",
    "codegen-api",
    "codegen-processor",
    "test",
]

[workspace.package]
version = "0.7.0"
edition = "2021"
license = "LGPL-3.0-or-later"
authors = ["Michael Schnell"]
repository = "https://github.com/fuinorg/ddd-4-rust"
